### ISSUE TITLE
Error compiling corto project on Windows 10

### ISSUE THREAD

**Issue by Vytek** [cnr-isti-vclab/corto#35]
I am trying to compile the project on: 

Microsoft Windows [Versione 10.0.19044.1586]

I am using CMake Gui for Windows Version:

![image](https://user-images.githubusercontent.com/2614303/161446471-9043413b-800b-46ba-8bae-15f8d03c43df.png)

Visual Studio Version:

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community Edition

Visual Basic 2015   00322-20000-00000-AA114
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA114
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA114
Microsoft Visual C++ 2015

CMake create the correct solution file:

![image](https://user-images.githubusercontent.com/2614303/161446596-8b519427-aa5e-4194-a020-a155e39737e3.png)

But when I am trying to build the solution:

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
2>------ Rebuild All started: Project: cortocodec_unity, Configuration: Debug x64 ------
2>  Building Custom Rule C:/Users/enric/Desktop/repo/corto-master/CMakeLists.txt
2>  bitstream.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\bitstream.cpp(21): fatal error C1083: Cannot open include file: 'bitstream.h': No such file or directory
2>  color_attribute.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\color_attribute.cpp(19): fatal error C1083: Cannot open include file: 'color_attribute.h': No such file or directory
2>  cstream.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\cstream.cpp(19): fatal error C1083: Cannot open include file: 'cstream.h': No such file or directory
2>  decoder.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\decoder.cpp(26): fatal error C1083: Cannot open include file: 'tunstall.h': No such file or directory
2>  encoder.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\encoder.cpp(24): fatal error C1083: Cannot open include file: 'zpoint.h': No such file or directory
2>  normal_attribute.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\normal_attribute.cpp(20): fatal error C1083: Cannot open include file: 'normal_attribute.h': No such file or directory
2>  tunstall.cpp
2>C:\Users\enric\Desktop\repo\corto-master\src\tunstall.cpp(25): fatal error C1083: Cannot open include file: 'tunstall.h': No such file or directory
2>  corto_codec.cpp
2>c:\users\enric\desktop\repo\corto-master\src\corto_codec.h(4): fatal error C1083: Cannot open include file: 'decoder.h': No such file or directory
2>  Generating Code...

Can you help me to fix the issue? Thank you very much!

Grazie di tutto e spero possiate aiutarmi! Saluti da un utente italiano ;-)

**Comment by ponchio** [comment]
The include path was wrong. Fixed.
Feel free to contact me if you need some support...

Ciao!

**Comment by Vytek** [comment]
Now all works fine!

Thank you very much!
