### ISSUE TITLE
Conflicting licenses

### ISSUE THREAD

**Issue by Louis-Simon22** [cnr-isti-vclab/corto#42]
Hello, 

We were considering using this libary, but found conflicting information regarding the licensing. In the LICENSE.txt, there seems to be the MIT license, but in the readme it says that the c++ part of the code is released under the GPL license.
Is the readme mention still accurate?

Thank you

**Comment by ponchio** [comment]
We decided to change the licence to MIT when asked about thre javascript code, since you are asking fot the C++ code too, we agreed to move it to MIT licence.
